# Generated by Django 3.0.5 on 2020-04-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200428_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
